apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "allow-ingress-{{ .Values.name }}-microservice"
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: "{{ .Values.name }}-app"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - protocol: TCP
          port: {{ .Values.container.port }} 

---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "allow-{{ .Values.name }}-microservice"
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app:  {{ .Values.ingress.appRelated }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "{{ .Values.name }}-app"
      ports:
        - protocol: TCP
          port: {{ .Values.container.port }}
{{- end }}